### ISSUE TITLE
Much features dont work

### ISSUE THREAD

**Issue by dejanmilosevic0** [christian-bromann/devtools-backend#15]
Screencasting don't work, nothing from rendering console drawer ( Paint flashing, layer borders.. )

Is this actually limitation of running in browser or it is just not implemented as i see that error is undefined function. 

Actually, what are basically limitations of running in browser, because native devtools which are packaged in browser are also using html/js application? I suppose that chrome is spawning server process but you are doing same also with node server. If you have time to answer i am really curious what are specific limitations and theoretically is there any possibility to create fully operational devtools clone which is running in browser with extensions ( which are plain html/js ) etc.

Thanks.

**Comment by christian-bromann** [comment]
Hey @demil,

> Is this actually limitation of running in browser or it is just not implemented as i see that error is undefined function.

Both. I implemented only a set of all domains and methods in the Chrome DevTools protocol. I would love to support more stuff but I had only a limited time working on this and now I moved to a different project.

Also since the instrumentation script can only do what JS provides in terms of functionality you won't be able to implement the full DevTools protocol. The goal of this project is to enable a minimum set of features to be able to debug web pages on arbitrary web environments where you usually don't have access to DevTools.

**Comment by dejanmilosevic0** [comment]
What part of dev-tools protocol for example can not be implemented and what is stoping it to be implemented, i mean it is all javascript, right?

**Comment by christian-bromann** [comment]
Stuff like [Runtime](https://chromedevtools.github.io/devtools-protocol/tot/Runtime) or [Tethering](https://chromedevtools.github.io/devtools-protocol/tot/Tethering) is impossible to support because there is no JS API to access that functionality. Same for screencasting.
